version: '3.3'
services:
  db:
    image: mysql:5.7
    platform: linux/x86_64
    restart: always
    environment:
      MYSQL_DATABASE: 'cozero'
      MYSQL_USER: 'cozero'
      MYSQL_PASSWORD: 'cozero'
      MYSQL_ROOT_PASSWORD: 'cozero'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - cozerodb:/var/lib/mysql
volumes:
  cozerodb: